-- The zvote schema.
--
-- Portable: it runs on H2 (development, tests) and on PostgreSQL, and so must
-- every migration after it. GENERATED BY DEFAULT AS IDENTITY, never
-- AUTO_INCREMENT (H2 and MySQL only); TIMESTAMP WITH TIME ZONE; BYTEA.
--
-- Table names are singular and never quoted, and the entities carry no @Table
-- annotation, so Spring Data derives the same names. An explicit @Table("x")
-- is a QUOTED identifier while derived column names are not, and the two then
-- disagree about case (H2 folds unquoted names up, PostgreSQL folds them down).
--
-- Nothing here says who chose what (docs/ARCHITECTURE.md, "Anonymity"). A
-- voter's ballot, name and invitation on a poll are each stored under a key of
-- their own, an HMAC of the voter's token under the server's secret (see
-- Voter.java), and no table records when anyone voted.
--
-- What a poll can hold billions of (ballots, names, invitations) has no
-- foreign key to it: deleting a poll lists it in poll_removal, and those rows
-- go afterwards, in batches (PollRetention), so that no transaction grows with
-- the size of a poll.

-- A question being decided.
CREATE TABLE poll (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The only external identifier: it appears in every URL, and for an
    -- unlisted poll it is also the secret that grants access.
    share_token           VARCHAR(32)  NOT NULL UNIQUE,
    -- A short stand-in for the share token, to type on a phone (K7M-4QX).
    join_code             VARCHAR(6)   NOT NULL UNIQUE,
    -- A hash of the creator's voter token, never the token itself.
    creator_id            VARCHAR(64)  NOT NULL,
    title                 VARCHAR(500) NOT NULL,
    voting_system         VARCHAR(32)  NOT NULL,
    visibility            VARCHAR(16)  NOT NULL,
    -- Chosen once, at creation: whether only invited people vote, whether
    -- voters may give a name, and when the results show while the poll is
    -- open: LIVE, AFTER_BALLOTS (once results_after_ballots are in) or
    -- AFTER_CLOSING. Watching tallies move as people vote shows what each one
    -- chose.
    invitation_only       BOOLEAN      NOT NULL,
    show_voter_names      BOOLEAN      NOT NULL,
    results_shown         VARCHAR(16)  NOT NULL,
    results_after_ballots BIGINT,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    -- NULL while the poll accepts ballots.
    closed_at             TIMESTAMP WITH TIME ZONE,
    CONSTRAINT poll_results_after_ballots
        CHECK (results_shown <> 'AFTER_BALLOTS' OR COALESCE(results_after_ballots, 0) >= 3)
);

CREATE INDEX poll_by_visibility ON poll (visibility, created_at);
CREATE INDEX poll_by_creator ON poll (creator_id, created_at);
-- Polls are deleted a while after they were created.
CREATE INDEX poll_by_age ON poll (created_at);

CREATE TABLE poll_option (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id  BIGINT       NOT NULL REFERENCES poll (id) ON DELETE CASCADE,
    position INT          NOT NULL,
    label    VARCHAR(500) NOT NULL,
    UNIQUE (poll_id, position)
);

-- A voter's whole ballot on one poll: one byte per option, in the options'
-- order (a mention's rank for majority judgment, 1 for an approved option).
CREATE TABLE ballot (
    poll_id    BIGINT      NOT NULL,
    ballot_key VARCHAR(64) NOT NULL,
    choices    BYTEA       NOT NULL,
    PRIMARY KEY (poll_id, ballot_key)
);

-- What each ballot changed, from what to what (null: no ballot), until the
-- change is folded into its poll's tallies, a moment later. Only inserted
-- while voting, so ballots never wait for each other on a counter.
CREATE TABLE ballot_change (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL,
    before  BYTEA,
    after   BYTEA
);

-- Tallies are stored, so that reading them costs the same at any size, and
-- can be rebuilt from the ballots at any time. tally: how many ballots give
-- each option each choice; ballot_count: how many ballots the poll has. A
-- poll gets them when it is created (TallyService.open).
CREATE TABLE tally (
    poll_id  BIGINT   NOT NULL REFERENCES poll (id) ON DELETE CASCADE,
    position SMALLINT NOT NULL,
    choice   SMALLINT NOT NULL,
    total    BIGINT   NOT NULL,
    PRIMARY KEY (poll_id, position, choice)
);

CREATE TABLE ballot_count (
    poll_id BIGINT NOT NULL PRIMARY KEY REFERENCES poll (id) ON DELETE CASCADE,
    total   BIGINT NOT NULL
);

-- The name a voter chose on one poll, while they hold a ballot on it, shown
-- to everyone on the poll. Names exist per poll only: nothing about a voter is
-- kept across polls.
CREATE TABLE voter_name (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id  BIGINT       NOT NULL,
    name_key VARCHAR(64)  NOT NULL,
    name     VARCHAR(100) NOT NULL,
    UNIQUE (poll_id, name_key)
);

-- The name cloud shows the first names in alphabetical order.
CREATE INDEX voter_name_by_name ON voter_name (poll_id, name);

-- The invitations to a poll that only invited people vote on are numbered
-- 1, 2, 3...: issued says how many its creator made, revoked how many they
-- took back. Their links are signed rather than stored (InvitationLinks), so
-- making a billion is one update. Only the creator writes these counters:
-- voters never wait on them.
CREATE TABLE invitation_count (
    poll_id BIGINT NOT NULL PRIMARY KEY REFERENCES poll (id) ON DELETE CASCADE,
    issued  BIGINT NOT NULL,
    revoked BIGINT NOT NULL
);

-- What is known of an invitation besides its number, if anything: whom the
-- creator made it for (label, shown to them only), the key of the browser
-- that voted with it (used_by), or that it was taken back. An invitation that
-- is none of these has no row. A browser uses one invitation per poll at most
-- (unused ones hold null, which the constraint ignores).
CREATE TABLE invitation (
    poll_id BIGINT      NOT NULL,
    number  BIGINT      NOT NULL,
    label   VARCHAR(100),
    used_by VARCHAR(64),
    revoked BOOLEAN     NOT NULL,
    PRIMARY KEY (poll_id, number),
    UNIQUE (poll_id, used_by)
);

-- Deleted polls whose ballots, names and invitations are still being removed.
CREATE TABLE poll_removal (
    poll_id BIGINT NOT NULL PRIMARY KEY
);
