-- V1: initial zvote schema.
--
-- Portable ANSI SQL: this runs on H2 locally and is meant to run unchanged on
-- PostgreSQL. Keep future migrations the same way - GENERATED BY DEFAULT AS
-- IDENTITY, never AUTO_INCREMENT (H2/MySQL only).
--
-- Vocabulary: a POLL is the question being decided. A BALLOT is one voter's
-- answer to it: an approval row per approved option, or a judgment row per
-- option. "Vote" was ambiguous between the two and is not used as a noun.
--
-- Table names are singular and never quoted, and the entities carry no @Table
-- annotation, so Spring Data derives the same names. An explicit @Table("x")
-- is a QUOTED identifier while derived column names are not, and the two then
-- disagree about case (H2 folds unquoted names up, PostgreSQL folds them down).
--
-- Tallies are never stored: one GROUP BY derives them from the ballot rows, so
-- there is no second source of truth to keep in sync.

CREATE TABLE poll (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The only external identifier: it appears in every URL, and for an
    -- unlisted poll it is also the secret that grants access.
    share_token   VARCHAR(32)  NOT NULL UNIQUE,
    -- A hash of the creator's voter token, never the token itself.
    creator_id    VARCHAR(64)  NOT NULL,
    title         VARCHAR(500) NOT NULL,
    voting_system VARCHAR(32)  NOT NULL,
    visibility    VARCHAR(16)  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    -- NULL while the poll accepts ballots.
    closed_at     TIMESTAMP WITH TIME ZONE
);

CREATE INDEX poll_by_visibility ON poll (visibility, created_at);
CREATE INDEX poll_by_creator ON poll (creator_id, created_at);

CREATE TABLE poll_option (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id  BIGINT       NOT NULL REFERENCES poll (id) ON DELETE CASCADE,
    position INT          NOT NULL,
    label    VARCHAR(500) NOT NULL,
    UNIQUE (poll_id, position)
);

-- Approval ballots: one row per approved option.
CREATE TABLE approval (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id   BIGINT      NOT NULL REFERENCES poll (id) ON DELETE CASCADE,
    option_id BIGINT      NOT NULL REFERENCES poll_option (id) ON DELETE CASCADE,
    voter_id  VARCHAR(64) NOT NULL,
    cast_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (voter_id, option_id)
);

CREATE INDEX approval_by_poll ON approval (poll_id, voter_id);

-- Majority judgment ballots: one mention per option.
CREATE TABLE judgment (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id   BIGINT      NOT NULL REFERENCES poll (id) ON DELETE CASCADE,
    option_id BIGINT      NOT NULL REFERENCES poll_option (id) ON DELETE CASCADE,
    voter_id  VARCHAR(64) NOT NULL,
    mention   VARCHAR(16) NOT NULL,
    cast_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (voter_id, option_id)
);

CREATE INDEX judgment_by_poll ON judgment (poll_id, voter_id);
