-- V2: join codes, voter names, and a way to find old polls.
--
-- Portable, like V1: it runs on H2 and on PostgreSQL.

-- A short code to type on a phone (K7M-4QX), besides the link. Polls created
-- before join codes existed get one taken from their random share token, so
-- that, like a drawn code, it cannot be guessed from other polls: 8 characters
-- of it, upper-cased, with the token's - and _ turned into letters (codes are
-- looked up by their letters and digits only).
ALTER TABLE poll ADD COLUMN join_code VARCHAR(8);
UPDATE poll SET join_code = TRANSLATE(UPPER(SUBSTRING(share_token FROM 1 FOR 8)), '-_', 'XY');
ALTER TABLE poll ALTER COLUMN join_code SET NOT NULL;
ALTER TABLE poll ADD CONSTRAINT poll_join_code UNIQUE (join_code);

-- Chosen by the creator, once: whether the poll shows who took part.
ALTER TABLE poll ADD COLUMN show_voter_names BOOLEAN DEFAULT FALSE NOT NULL;

-- Polls are deleted a while after they were created.
CREATE INDEX poll_by_age ON poll (created_at);

-- The name a voter chose on one poll, while they hold a ballot on it. Never
-- linked to what they chose: it is stored under a key of its own (name_key,
-- see Voter.java), which no ballot shares, and records no time. Names exist
-- per poll only; nothing about a voter is kept across polls. No foreign key:
-- a poll's names can be millions, so they go in batches after the poll
-- (poll_removal, V3) rather than in the poll's own deletion.
CREATE TABLE voter_name (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id   BIGINT       NOT NULL,
    name_key  VARCHAR(64)  NOT NULL,
    name      VARCHAR(100) NOT NULL,
    UNIQUE (poll_id, name_key)
);

-- The name cloud shows the first names in alphabetical order.
CREATE INDEX voter_name_by_name ON voter_name (poll_id, name);
