-- V2: join codes, voter names, and a way to find old polls.
--
-- Portable, like V1: it runs on H2 and on PostgreSQL.

-- A short code to type on a phone (K7M-4QX), besides the link. Polls created
-- before join codes existed get one derived from their id: codes are looked
-- up exactly, so it does not matter that it is not in the generated alphabet.
ALTER TABLE poll ADD COLUMN join_code VARCHAR(8);
UPDATE poll SET join_code = 'Z' || CAST(id AS VARCHAR(7));
ALTER TABLE poll ALTER COLUMN join_code SET NOT NULL;
ALTER TABLE poll ADD CONSTRAINT poll_join_code UNIQUE (join_code);

-- Chosen by the creator, once: whether the poll shows who took part.
ALTER TABLE poll ADD COLUMN show_voter_names BOOLEAN DEFAULT FALSE NOT NULL;

-- Polls are deleted a while after they were created.
CREATE INDEX poll_by_age ON poll (created_at);

-- The name a voter chose on one poll, while they hold a ballot on it. Never
-- linked to what they chose: the ballot rows do not refer to it. Names exist
-- per poll only; nothing about a voter is kept across polls.
CREATE TABLE voter_name (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id   BIGINT       NOT NULL REFERENCES poll (id) ON DELETE CASCADE,
    voter_id  VARCHAR(64)  NOT NULL,
    name      VARCHAR(100) NOT NULL,
    named_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (poll_id, voter_id)
);
