-- V3: ballots that say nothing about who cast them, and scale to billions.
--
-- Portable, like V1: it runs on H2 and on PostgreSQL.
--
-- One row per ballot (not one per option and voter), keyed per poll by an
-- HMAC of the voter's token under a server secret (see Voter.java): no time,
-- no voter id, nothing that leads back to the voter, or to their name. The
-- ballots cast so far, one row per option, cannot be turned into that (the
-- tokens were never stored): they go. Nothing was in production yet.
DROP TABLE approval;
DROP TABLE judgment;

-- Chosen by the creator, once: when the results show. Watching them move as
-- people vote shows what each one chose. LIVE, AFTER_BALLOTS (once
-- results_after_ballots ballots are in) or AFTER_CLOSING.
ALTER TABLE poll ADD COLUMN results_shown VARCHAR(16) DEFAULT 'LIVE' NOT NULL;
ALTER TABLE poll ADD COLUMN results_after_ballots BIGINT;
ALTER TABLE poll ADD CONSTRAINT poll_results_after_ballots
    CHECK (results_shown <> 'AFTER_BALLOTS' OR COALESCE(results_after_ballots, 0) >= 3);

-- A voter's whole ballot on one poll: one byte per option, in the options'
-- order (a mention's rank for majority judgment, 1 for an approved option).
-- No foreign key: a poll's ballots can be billions, so they go in batches
-- after the poll (poll_removal, below) rather than in one deletion.
CREATE TABLE ballot (
    poll_id    BIGINT      NOT NULL,
    ballot_key VARCHAR(64) NOT NULL,
    choices    BYTEA       NOT NULL,
    PRIMARY KEY (poll_id, ballot_key)
);

-- What each ballot changed, from what to what (null: no ballot), until the
-- change is folded into its poll's tallies, a moment later. Only inserted
-- while voting, so ballots never wait for each other on a counter.
CREATE TABLE ballot_change (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL,
    before  BYTEA,
    after   BYTEA
);

-- Tallies are stored, so that reading them costs the same at any size, and
-- can be rebuilt from the ballots at any time. tally: how many ballots give
-- each option each choice; ballot_count: how many ballots the poll has.
CREATE TABLE tally (
    poll_id  BIGINT   NOT NULL REFERENCES poll (id) ON DELETE CASCADE,
    position SMALLINT NOT NULL,
    choice   SMALLINT NOT NULL,
    total    BIGINT   NOT NULL,
    PRIMARY KEY (poll_id, position, choice)
);

CREATE TABLE ballot_count (
    poll_id BIGINT NOT NULL PRIMARY KEY REFERENCES poll (id) ON DELETE CASCADE,
    total   BIGINT NOT NULL
);

-- Existing polls start from zero, like new ones (TallyService.open): 2 choices
-- per option for approval (not approved, approved), 7 for majority judgment.
INSERT INTO ballot_count (poll_id, total) SELECT id, 0 FROM poll;
INSERT INTO tally (poll_id, position, choice, total)
SELECT o.poll_id, o.position, c.choice, 0
FROM poll_option o
JOIN poll p ON p.id = o.poll_id
JOIN (VALUES (0), (1), (2), (3), (4), (5), (6)) AS c (choice)
    ON c.choice < CASE p.voting_system WHEN 'APPROVAL' THEN 2 ELSE 7 END;

-- Deleted polls whose ballots and names are still being removed, in batches.
CREATE TABLE poll_removal (
    poll_id BIGINT NOT NULL PRIMARY KEY
);
