-- V4: invitation polls, where each voter gets a link of their own.
--
-- Portable, like V1: it runs on H2 and on PostgreSQL.

-- Chosen by the creator, once: only the people they invite may vote.
ALTER TABLE poll ADD COLUMN invitation_only BOOLEAN DEFAULT FALSE NOT NULL;

-- One link per voter, made by the poll's creator, who sends it. token: the
-- secret in the link. label: who it is for, as the creator wrote it, shown to
-- them only. used_by: the key of the browser that voted with it (see
-- Voter.java), which matches no ballot and no name: the creator learns that
-- it was used, never what its voter chose, and nothing records when. A
-- browser uses one invitation per poll at most (unused ones hold null, which
-- the constraint ignores). A poll has at most max-invitations of them, so,
-- unlike its ballots, they go with it in one deletion.
CREATE TABLE invitation (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id BIGINT       NOT NULL REFERENCES poll (id) ON DELETE CASCADE,
    token   VARCHAR(32)  NOT NULL UNIQUE,
    label   VARCHAR(100),
    used_by VARCHAR(64),
    UNIQUE (poll_id, used_by)
);
